FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src


COPY src/Worker/Worker.csproj src/Worker/
RUN dotnet restore src/Worker/Worker.csproj

COPY . .
RUN dotnet publish src/Worker/Worker.csproj -c Release -o /app/publish 

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish ./

ENTRYPOINT [ "dotnet", "Worker.dll" ]